### ISSUE TITLE
Fix indentation and spacing issues in repository

### ISSUE THREAD

**Issue by djmcdonald** [Spedge/hangar#3]
The repo seems to have inconsistent spacing and indentation in areas making reading code somewhat difficult.

Perhaps some form of [linting](https://github.com/checkstyle/checkstyle) could be added as part of the build process or usage of something like [EditorConfig?](http://editorconfig.org/) to maintain consistent code style - it could be argued this is high priority as the project is relatively new and creating a PR to change whitespace, etc in a mature project would be a difficult code review.

**Comment by Spedge** [comment]
Agreed - and thanks for the suggestion. I'll take a look into it.

**Comment by Spedge** [comment]
Added the checkstyle formatting.
