### ISSUE TITLE
Implement dependency injection for Hangar

### ISSUE THREAD

**Issue by djmcdonald** [Spedge/hangar#7]
I've not looked through the code in its entirety, but it looks like there's no dependency injection? i.e.: 
https://github.com/Spedge/hangar/blob/master/hangar-api/src/main/java/com/spedge/hangar/repo/java/JavaRepository.java#L61

Would be worth adding this to Hangar to aid testing and handling of class dependencies.

Some potential IoC libs:
- https://github.com/google/guice
- http://picocontainer.com/

**Comment by djmcdonald** [comment]
Just to say, I'd be happy to add this when I get some free time.

**Comment by Spedge** [comment]
Excellent - thanks for pointing this out. Not done much with dependency injection, so happy to take it on board if it's going to be useful.

Also, will be starting to do some refactoring to start Python support - no doubt the assumptions I made around where the interfaces should go will have been perfect, but there may be one or two ;)
